language: python
python:
   - "3.7"

before_install:
    - curl https://raw.githubusercontent.com/kennethreitz/pipenv/master/get-pipenv.py | python

install:
    - pipenv install

script:
    - pipenv run python triangularregressor.py
    
